version: '3.8'

services:
  chinese-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chinese-app
    restart: unless-stopped
    ports:
      - "9999:3000"
    environment:
      - NODE_ENV=production
      - MINIO_ENABLED=true
      - MINIO_ENDPOINT=192.168.1.13
      - MINIO_PORT=9000
      - MINIO_SECURE=false
      - MINIO_ACCESS_KEY=admin
      - MINIO_SECRET_KEY=admin12345
      - MINIO_BUCKET_NAME=image
      - MINIO_PUBLIC_URL=minio.ovenx.shop
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
